Clean w4
bigladder/libtess2 pull request #3
Opened 2022-10-04 22:03 UTC by galanCA

Clean some level 4 warnings in MSVC.

- Fix int to char conversion. This is fixed by casting `(char)`.
- Fix uninitialized variables by initializing it to 0 if its a variable or NULL if its a pointer.

2022-10-05 14:38 UTC, nealkruis requested changes

2022-10-05 14:38 UTC, nealkruis commented on Source/tess.c
> +	TESSreal maxVal[3] = {0}, minVal[3] = {0}, d1[3] = {0}, d2[3] = {0}, tNorm[3] = {0};
Is this valid C syntax?

2022-10-06 14:08 UTC, galanCA commented on Source/tess.c
> +	TESSreal maxVal[3] = {0}, minVal[3] = {0}, d1[3] = {0}, d2[3] = {0}, tNorm[3] = {0};
@nealkruis Only for zero but yes. [This article](https://www.digitalocean.com/community/tutorials/initialize-an-array-in-c#:~:text=If%20you%20want%20to%20initialize%20all%20the%20elements%20to%200%2C%20there%20is%20a%20shortcut%20for%20this%20(Only%20for%200).%20We%20can%20simply%20mention%20the%20index%20as%200.) gives a small explanation.

2022-10-14 18:17 UTC, nealkruis approved these changes

2022-10-14 18:18 UTC, merged